apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-init-sql
  namespace: default
data:
  init.sql: |
    -- This SQL creates a schema in the target database.
    -- The Job below will run this file against `DBATools`.
    CREATE SCHEMA IF NOT EXISTS default AUTHORIZATION appuser;

# Edit namespace, database name and schema as needed.
