apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-appuser.yaml
  - pg-cluster.yml
  - database-cr.yaml
  - init-configmap.yaml
  - init-job.yaml
namespace: default
