apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgadmin

commonLabels:
  app: pgadmin

resources:
  - namespace-pgadmin.yaml
  - secret-pgadmin.yaml
  - pvc-pgadmin.yaml
  - deployment-pgadmin.yaml
  - service-pgadmin.yaml
