apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-operator-sa
  namespace: dns-mngr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-operator-role
  namespace: dns-mngr
rules:
  - apiGroups: ["example.com"]
    resources: ["dnsrecords"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["example.com"]
    resources: ["dnsrecords/status"]
    verbs: ["get","update","patch"]
  - apiGroups: [""]
    resources: ["services","endpoints","secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-operator-rb
  namespace: dns-mngr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-operator-role
subjects:
  - kind: ServiceAccount
    name: dns-operator-sa
    namespace: dns-mngr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-operator
  namespace: dns-mngr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-operator
  template:
    metadata:
      labels:
        app: dns-operator
    spec:
      serviceAccountName: dns-operator-sa
      containers:
        - name: dns-operator
          image: docker.io/kigarsk/dns-operator:0.1.0
          imagePullPolicy: Always
          env:
            - name: IPA_SERVER
              value: "https://lipar1.axiome-it.lan"
            - name: IPA_CRED_SECRET
              value: "freeipa-credentials"
            - name: OP_NS
              value: "dns-mngr"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20

