apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-operator
  namespace: dns-mngr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-operator
  template:
    metadata:
      labels:
        app: dns-operator
    spec:
      serviceAccountName: dns-operator-sa
      containers:
        - name: dns-operator
          image: docker.io/kigarsk/dns-operator:0.1.0
          imagePullPolicy: Always
          env:
            - name: IPA_SERVER
              value: "https://lipar1.axiome-it.lan"
            - name: IPA_CRED_SECRET
              value: "freeipa-credentials"
            - name: OP_NS
              value: "dns-mngr"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20

