apiVersion: example.com/v1
kind: DNSRecord
metadata:
  name: tst-record
spec:
  name: tst.axiome-it.lan.
  zone: axiome-it.lan.
  type: A
  serviceNamespace: ingress-nginx
  serviceName: ingress-nginx-controller
  ttl: 300

