apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-operator-kube-system-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: dns-operator-sa
    namespace: dns-mngr
