# role-events.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-operator-events
  namespace: dns-mngr
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-operator-role
  namespace: dns-mngr
rules:
  - apiGroups: ["example.com"]
    resources: ["dnsrecords"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["example.com"]
    resources: ["dnsrecords/status"]
    verbs: ["get","update","patch"]
  - apiGroups: [""]
    resources: ["services","secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-operator-rb
  namespace: dns-mngr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-operator-role
subjects:
  - kind: ServiceAccount
    name: dns-operator-sa
    namespace: dns-mngr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-operator-crd-reader
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-operator-crd-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-operator-crd-reader
subjects:
  - kind: ServiceAccount
    name: dns-operator-sa
    namespace: dns-mngr
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-operator-clusterrole
rules:
  - apiGroups: ["example.com"]
    resources: ["dnsrecords", "dnsrecords/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-operator-clusterrole
subjects:
  - kind: ServiceAccount
    name: dns-operator-sa
    namespace: dns-mngr
---
# rolebinding-events.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-operator-events-binding
  namespace: dns-mngr
subjects:
- kind: ServiceAccount
  name: dns-operator-sa
  namespace: dns-mngr
roleRef:
  kind: Role
  name: dns-operator-events
  apiGroup: rbac.authorization.k8s.io

